services:

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  order-service:
    build: ./order_service
    depends_on:
      - redis
    environment:
      PYTHONUNBUFFERED: 1

  notification-service:
    build: ./notification_service
    depends_on:
      - redis
    environment:
      PYTHONUNBUFFERED: 1